In [1]:
import os, sys
import numpy as np
import matplotlib.pyplot as plt

In [2]:
sys.path.append('../readmaroc/')

In [3]:
from maroc_data import MarocData, Header

In [4]:
fname = '../data/0802/Run000087881.dat'

In [67]:
data = MarocData(fname)
for b in data.active_boards:
    events = np.asarray([Header(i).trigg_n_TS for i in data.header_board(b)])[1:]
    nevt = data.nevents_per_board(b)
    diff = np.setdiff1d(np.arange(nevt)[1:], np.unique(events))
    print('board {}, n_events: {}, unique id: {}'.format(b, nevt-1, np.unique(events).shape[0]))
    if len(diff):
        print('\tmissing evt id: {}'.format(diff))
    #print(np.arange(data.nevents_per_board(b))[np.setdiff1d(np.unique(events), np.arange(data.nevents_per_board(b)))])

board 1, n_events: 1200, unique id: 1200
board 2, n_events: 1200, unique id: 1200
board 3, n_events: 1200, unique id: 1198
	missing evt id: [475 535]
board 4, n_events: 1200, unique id: 1200
board 5, n_events: 1200, unique id: 1199
	missing evt id: [610]
board 6, n_events: 1200, unique id: 1200
board 7, n_events: 1200, unique id: 1200
board 8, n_events: 1200, unique id: 1200
board 9, n_events: 1200, unique id: 1199
	missing evt id: [1046]
board 10, n_events: 1200, unique id: 1199
	missing evt id: [1035]
board 11, n_events: 1200, unique id: 1200
board 12, n_events: 1199, unique id: 1198
	missing evt id: [252]
board 13, n_events: 1199, unique id: 1199
board 14, n_events: 1199, unique id: 1198
	missing evt id: [865]
board 15, n_events: 1199, unique id: 1199
board 16, n_events: 1199, unique id: 1198
	missing evt id: [594]
board 17, n_events: 1199, unique id: 1199
board 18, n_events: 1199, unique id: 1199
board 19, n_events: 1199, unique id: 1198
	missing evt id: [740]
board 20, n_events: 1

In [50]:
events = np.asarray([Header(i).trigg_n_TS for i in data.header_board(1)])

In [52]:
np.unique(events)
np.where(np.arange(1201) - np.unique(events))

(array([   0,    1,    2, ..., 1198, 1199, 1200]),)

In [53]:
np.intersect1d(np.arange(1201), np.unique(events))

array([   1,    2,    3, ..., 1198, 1199, 1200])

In [58]:
np.arange(1201)[np.setdiff1d(np.arange(1201), np.unique(events[1:]))]

array([0])

In [46]:
events[994]

995

In [47]:
events[992:997]

array([992, 994, 995, 996, 997])

In [33]:
np.setdiff1d(np.unique(events), np.arange(1201))

array([2312230670])