In [1]:
import os, sys
import numpy as np
import matplotlib.pyplot as plt

In [2]:
sys.path.append('../readmaroc/')

In [3]:
from maroc_data import MarocData, Header

In [5]:
fname = '../data/0802/Run000087881.dat'

In [6]:
%matplotlib qt

In [7]:
b = 27

maroc_data = MarocData(fname)
for b in maroc_data.active_boards[25:27]: 
    print(b)
    board_data = maroc_data.header_board(b)
    n_events = len(board_data)
    ts = np.asarray([Header(i).TS for i in board_data])
    nevent = np.asarray([Header(i).trigg_n_TS for i in board_data])
    plt.plot(nevent[1:], ts[1:], '-o',label='board {}'.format(b),
            markersize=3, marker='x')
            #plt.legend(loc='upper right')

plt.legend(loc='upper right')
plt.show()


27
28


In [8]:
b = 27

maroc_data = MarocData(fname)
for b in maroc_data.active_boards[25:27]: 
    
    board_data = maroc_data.header_board(b)
    n_events = len(board_data)
    
    ts = np.asarray([Header(i).TS for i in board_data])
    nevent = np.asarray([Header(i).trigg_n_TS for i in board_data])

    for i, evt in enumerate(nevent):
        print(i, evt, ts[i])


0 1372784146 1372784154
1 1 28700201
2 2 36552385
3 3 47363236
4 4 64165343
5 5 76730408
6 6 79287381
7 7 83537510
8 8 84644615
9 9 85406986
10 10 131409170
11 11 136986039
12 12 141660587
13 13 192698125
14 14 205263714
15 15 209916397
16 16 225107807
17 17 249404336
18 18 249437684
19 19 259699993
20 20 268803874
21 21 284334048
22 22 293422500
23 23 294926642
24 24 338416793
25 25 364436733
26 26 376208432
27 27 401250900
28 28 421849181
29 29 434235888
30 30 434448417
31 31 435634623
32 32 445933504
33 33 457444872
34 34 467600348
35 35 472343714
36 36 474256151
37 37 480461044
38 38 496241416
39 39 505020570
40 40 515213876
41 41 521361377
42 42 522944886
43 43 527475501
44 44 535925744
45 45 628267645
46 46 629955003
47 47 640739056
48 48 648179620
49 49 651298789
50 50 662378651
51 51 728089615
52 52 743301543
53 53 763562845
54 54 767576128
55 55 773533967
56 56 783851633
57 57 798599208
58 58 837753645
59 59 852260438
60 60 884159879
61 61 890200535
62 62 910199834
63 63 94384

744 744 2281741403
745 745 2292780350
746 746 2327338039
747 747 2330298202
748 748 2347912480
749 749 2363720560
750 750 2375723736
751 751 2392704636
752 752 2401748864
753 753 2423969507
754 754 2426509403
755 755 2442646755
756 756 2461626351
757 757 2468486784
758 758 2477188367
759 759 2480361730
760 760 2482876405
761 761 2506169383
762 762 2556966242
763 763 2591535460
764 764 2594623170
765 765 2641403988
766 766 2642890839
767 767 2648413954
768 768 2682872849
769 769 2693270308
770 770 2744436950
771 771 2754722364
772 772 2786091602
773 773 2809230606
774 774 2831843525
775 775 2835816041
776 776 2851476156
777 777 2854255241
778 778 2880485163
779 779 2880861319
780 780 2885700218
781 781 2899484367
782 782 2929683304
783 783 2937140769
784 784 2948296060
785 785 2950773564
786 786 2956745753
787 787 2980508700
788 788 2993723572
789 789 2995795001
790 790 3003274102
791 791 3003313635
792 792 3004273681
793 793 3009501046
794 794 3048333917
795 795 3058491874
796 796 3062

44 44 533357482
45 45 625699384
46 46 627386742
47 47 638170795
48 48 645611358
49 49 648730528
50 50 659810389
51 51 725521354
52 52 740733282
53 53 760994583
54 54 765007867
55 55 770965705
56 56 781283371
57 57 796030946
58 58 835185383
59 59 849692177
60 60 881591618
61 61 887632273
62 62 907631572
63 63 941280190
64 64 944456909
65 65 963719506
66 66 965464780
67 67 974514758
68 68 984123651
69 69 992439346
70 70 1016933633
71 71 1046386994
72 72 1057209832
73 73 1109076957
74 74 1146148568
75 75 1157441819
76 76 1168176156
77 77 1191010713
78 78 1192443386
79 79 1224927709
80 80 1230185773
81 81 1245188291
82 82 1247630300
83 83 1256945726
84 84 1269542964
85 85 1274742497
86 86 1294848009
87 87 1296703002
88 88 1303088005
89 89 1323860029
90 90 1324732772
91 91 1330535972
92 92 1355355608
93 93 1387345981
94 94 1397050936
95 95 1398620182
96 96 1415615750
97 97 1416485575
98 98 1432893872
99 99 1444606865
100 100 1458455953
101 101 1475972923
102 102 1515613136
103 103 153000263

544 544 3867102900
545 545 3870597718
546 546 3871279072
547 547 3885963072
548 548 3890919737
549 549 3898088769
550 550 3906060968
551 551 3927993190
552 552 3938861366
553 553 3939144561
554 554 3946840461
555 555 3950511992
556 556 3955949100
557 557 4029043611
558 558 4064315026
559 559 4072138887
560 560 4097457931
561 561 4134297493
562 562 4138571919
563 563 4143416447
564 564 4181937704
565 565 4185534911
566 566 4188664298
567 567 4197515086
568 568 4198541889
569 569 4222105688
570 570 4227900854
571 571 4239432098
572 572 4245149051
573 573 4266278970
574 574 4275249751
575 575 4277283338
576 576 4283412681
577 577 4286523626
578 578 1308046
579 579 5019080
580 580 19996474
581 581 41353464
582 582 55604989
583 583 56632645
584 584 81137427
585 585 82154217
586 586 101411080
587 587 105280241
588 588 110292378
589 589 114962081
590 590 120250330
591 591 126830053
592 592 152387845
593 593 156081894
594 594 178754282
595 595 179624317
596 596 196893833
597 597 207515445
598 

In [13]:
ts_27 = np.asarray([Header(i).TS for i in maroc_data.header_board(27)])[1:]
nevent_27 = np.asarray([Header(i).trigg_n_TS for i in maroc_data.header_board(27)][1:])
ts_28 = np.asarray([Header(i).TS for i in maroc_data.header_board(28)])[1:]
nevent_28 = np.asarray([Header(i).trigg_n_TS for i in maroc_data.header_board(28)][1:])

In [14]:
nevent_27

array([   1,    2,    3, ..., 1198, 1199, 1200])

In [19]:
nevent_28

array([   1,    2,    3, ..., 1198, 1199, 1200])

In [132]:
np.where(nevent_27==np.delete(nevent_28, 992))[0]

array([   0,    1,    2, ..., 1196, 1197, 1198])

In [127]:
nevent_27

array([   1,    2,    3, ..., 1198, 1199, 1200])

In [130]:
np.delete(nevent_28, 992)

array([   1,    2,    3, ..., 1198, 1199, 1200])

In [133]:
ts_27[np.where(nevent_27==np.delete(nevent_28, 992))[0]]-ts_28[np.where(nevent_27==np.delete(nevent_28, 992))[0]]

array([ 2568261,  2568262,  2568261, ...,  3155224, 16174547, 14969212])

In [22]:
nevent_27.shape

(1199,)

In [23]:
nevent_28.shape

(1200,)

In [10]:
ts_27.shape, ts_28.shape

((1199,), (1200,))

In [26]:
nevent_27[990:1000]

array([ 991,  992,  994,  995,  996,  997,  998,  999, 1000, 1001])

In [27]:
nevent_28[990:1000]

array([ 991,  992,  993,  994,  995,  996,  997,  998,  999, 1000])

In [30]:
plt.scatter(np.arange(1199), ts_27, s=1)
plt.scatter(np.arange(1200), ts_28, s=1)
plt.show()

In [12]:
for (j, i27), (k, i28) in zip(enumerate(ts_27), enumerate(np.delete(ts_28, 992))):
    if np.abs(i27-i28)>2568262:
        print(j,k, i27, i28, np.abs(i27-i28))

1142 1142 3771691327 3768968301 2723026


In [48]:
np.delete(ts_28, 992)

array([ 26131940,  33984123,  44794975, ..., 107637748, 121244034,
       133644985])

In [46]:
ts_28[991]-ts_27[991]

-2568262

In [68]:
np.split(np.asarray(maroc_data.active_boards)[:10], 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [169]:
boards = np.arange(1,31)
np.vstack(np.split(boards, (10))[5:])

array([[16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [198]:
vertical_stack = np.vstack(np.split(boards, (10))[5:])[:,1]
for (i, j) in zip(vertical_stack, vertical_stack[1:]):
    if i in maroc_data.active_boards and j in maroc_data.active_boards:
        ts_1 = np.asarray([Header(i).TS for i in maroc_data.header_board(i)])[1:]
        ts_2 = np.asarray([Header(i).TS for i in maroc_data.header_board(j)])[1:]
        shape_1 = ts_1.shape[0]
        shape_2 = ts_2.shape[0]
        if shape_1==shape_2:
            
            print("boards {}-{}: {}".format(i,j, np.abs(np.mean(ts_1-ts_2))))
            print(np.min(ts_1-ts_2), np.max(ts_1-ts_2), np.mean(ts_1-ts_2))
        else:
            print(i, j, shape_1, shape_2)
            if shape_1>shape_2:
                ts_2 = np.pad(ts_2, (0, shape_1-shape_2), 'constant')
            elif shape_2>shape_1:
                ts_1 = np.pad(ts_1, (0,shape_2-shape_1), 'constant')
            max_shape = np.max([shape_1, shape_2])
            plt.plot(np.arange(max_shape), np.abs(ts_1-ts_2), '-o',c='blue',  marker='s', markersize=2, alpha=.5, linewidth=1)
            #plt.plot(np.arange(max_shape), np.abs(ts_2-ts_1), '-o', c='red', marker='x',markersize=2)
            #if np.abs(ts_1-ts_2)>np.abs(ts_1[0]-ts_2[0]):
            #    print("boards{}-{}: i: {}, j: {}, value_i: {}, value_j:{}, diff: {}, mean_diff:{}".format(i, j, k, l, i1, i2, np.abs(i1-i2), np.abs(ts_1[0]-ts_2[0])))
            plt.show()
    else:
        pass

17 20 1199 1200
boards 20-23: 2059029.0891666666
-4289883256 23336231 -2059029.0891666666
boards 23-26: 1211602.2383333333
-4289005410 5961887 -1211602.2383333333
boards 26-29: 5263693.901666666
5252681 18467553 5263693.901666666


In [ ]:
vertical_stack = np.vstack(np.split(boards, (10))[5:])[:,1]
for (i, j) in zip(vertical_stack, vertical_stack[1:]):
    if i in maroc_data.active_boards and j in maroc_data.active_boards:
        ts_1 = np.asarray([Header(i).TS for i in maroc_data.header_board(i)])[1:]
        ts_2 = np.asarray([Header(i).TS for i in maroc_data.header_board(j)])[1:]
        shape_1 = ts_1.shape[0]
        shape_2 = ts_2.shape[0]
        if shape_1==shape_2:
            
            print("boards {}-{}: {}".format(i,j, np.abs(np.mean(ts_1-ts_2))))
            print(np.min(ts_1-ts_2), np.max(ts_1-ts_2), np.mean(ts_1-ts_2))
        else:
            print(i, j, shape_1, shape_2)
            if shape_1>shape_2:
                ts_2 = np.pad(ts_2, (0, shape_1-shape_2), 'constant')
            elif shape_2>shape_1:
                ts_1 = np.pad(ts_1, (0,shape_2-shape_1), 'constant')
            max_shape = np.max([shape_1, shape_2])
            plt.plot(np.arange(max_shape), np.abs(ts_1-ts_2), '-o',c='blue',  marker='s', markersize=2, alpha=.5, linewidth=1)
            #plt.plot(np.arange(max_shape), np.abs(ts_2-ts_1), '-o', c='red', marker='x',markersize=2)
            #if np.abs(ts_1-ts_2)>np.abs(ts_1[0]-ts_2[0]):
            #    print("boards{}-{}: i: {}, j: {}, value_i: {}, value_j:{}, diff: {}, mean_diff:{}".format(i, j, k, l, i1, i2, np.abs(i1-i2), np.abs(ts_1[0]-ts_2[0])))
            plt.show()
    else:
        pass

In [176]:
ts_17 = np.asarray([Header(i).TS for i in maroc_data.header_board(17)])[1:]
ts_20 = np.asarray([Header(i).TS for i in maroc_data.header_board(20)])[1:]
ts_24 = np.asarray([Header(i).TS for i in maroc_data.header_board(24)])[1:]
ts_27 = np.asarray([Header(i).TS for i in maroc_data.header_board(27)])[1:]
ts_28 = np.asarray([Header(i).TS for i in maroc_data.header_board(28)])[1:]
ts_29 = np.asarray([Header(i).TS for i in maroc_data.header_board(29)])[1:]
ts_30 = np.asarray([Header(i).TS for i in maroc_data.header_board(30)])[1:]

In [190]:
for (i1,t1), (i2,t2) in zip(enumerate(ts_17), enumerate(ts_20)):
    print(i1, i2, t1-t2)

0 0 5883664
1 1 5883664
2 2 5883664
3 3 5883664
4 4 5883664
5 5 5883664
6 6 5883664
7 7 5883664
8 8 5883664
9 9 5883664
10 10 5883664
11 11 5883664
12 12 5883664
13 13 5883664
14 14 5883664
15 15 5883664
16 16 5883664
17 17 5883664
18 18 5883664
19 19 5883664
20 20 5883664
21 21 5883664
22 22 5883664
23 23 5883664
24 24 5883664
25 25 5883664
26 26 5883664
27 27 5883664
28 28 5883664
29 29 5883664
30 30 5883664
31 31 5883664
32 32 5883664
33 33 5883664
34 34 5883664
35 35 5883664
36 36 5883664
37 37 5883664
38 38 5883664
39 39 5883664
40 40 5883664
41 41 5883664
42 42 5883664
43 43 5883664
44 44 5883664
45 45 5883664
46 46 5883664
47 47 5883664
48 48 5883664
49 49 5883664
50 50 5883664
51 51 5883664
52 52 5883664
53 53 5883664
54 54 5883664
55 55 5883664
56 56 5883664
57 57 5883664
58 58 5883664
59 59 5883664
60 60 5883664
61 61 5883664
62 62 5883664
63 63 5883663
64 64 5883664
65 65 5883664
66 66 5883664
67 67 5883664
68 68 5883664
69 69 5883664
70 70 5883664
71 71 5883664
72 72 588366

683 683 5883664
684 684 5883664
685 685 5883664
686 686 5883664
687 687 5883664
688 688 5883664
689 689 5883664
690 690 5883664
691 691 5883664
692 692 5883664
693 693 5883664
694 694 5883664
695 695 5883664
696 696 5883664
697 697 5883664
698 698 5883664
699 699 5883664
700 700 5883664
701 701 5883664
702 702 5883664
703 703 5883664
704 704 5883664
705 705 5883664
706 706 5883664
707 707 5883664
708 708 5883664
709 709 5883664
710 710 5883664
711 711 5883664
712 712 5883664
713 713 5883664
714 714 5883664
715 715 5883664
716 716 5883664
717 717 5883664
718 718 5883664
719 719 5883664
720 720 5883664
721 721 5883663
722 722 5883663
723 723 5883664
724 724 5883664
725 725 5883664
726 726 5883664
727 727 5883664
728 728 5883664
729 729 5883664
730 730 5883664
731 731 5883664
732 732 5883664
733 733 5883664
734 734 5883664
735 735 5883664
736 736 5883664
737 737 5883664
738 738 5883664
739 739 5883664
740 740 5883664
741 741 5883664
742 742 5883664
743 743 5883664
744 744 5883664
745 745 

In [181]:
ts_17.shape

(1199,)

In [182]:
ts_20.shape

(1200,)

In [191]:
plt.scatter(np.arange(len(ts_17)), ts_17, s=2, c='blue')
plt.scatter(np.arange(len(ts_20)), ts_20, s=2, c='red')
plt.show()

In [148]:
plt.scatter(np.arange(1199), ts_27, s=2)
plt.scatter(np.arange(1199),np.delete(ts_28, 992), s=2)
plt.show()

In [203]:
for bi, bj in zip(maroc_data.active_boards, maroc_data.active_boards[1:]):
    ts_i = np.asarray([Header(i).TS for i in maroc_data.header_board(bi)])[1:]
    ts_j = np.asarray([Header(i).TS for i in maroc_data.header_board(bj)])[1:]
    print(bi, bj, np.mean(ts_j[:1190]-ts_i[:1190]))
    



1 2 -2412759.7462184876
2 3 -1259210.9008403362
3 4 792466.3848739496
4 5 -2335669.377310924
5 6 -2828492.124369748
6 7 5560843.912605042
7 8 890793.9655462184
8 9 -1110894.6420168066
9 10 -2388958.4840336135
10 11 -1436159.412605042
11 12 578646.4638655462
12 13 7840125.11512605
13 14 -1395347.5151260504
14 15 -2364784.449579832
15 16 2294743.562184874
16 17 -2386250.787394958
17 18 1251698.6957983193
18 19 2326295.7403361346
19 20 -2243225.987394958
20 22 -256983.35882352942
22 23 2376038.2336134454
23 24 1302642.2302521009
24 25 -1221444.043697479
25 26 1190685.4731092437
26 27 -2547544.4823529413
27 28 -1436493.8176470587
28 29 -1279748.143697479
29 30 965455.5327731093


In [227]:
ts_27+1436493.8176470587

array([3.01366948e+07, 3.79888788e+07, 4.87997298e+07, ...,
       1.11642503e+08, 1.25248789e+08, 1.37649740e+08])

In [228]:
ts_28

array([ 26131940,  33984123,  44794975, ..., 107637748, 121244034,
       133644985])

In [230]:
plt.scatter(np.arange(len(ts_27)), ts_27-1436493.8176470587, s=1)
plt.scatter(np.arange(len(ts_28)), ts_28, s=1)

In [226]:
np.isclose(ts_30,ts_29-965455.5327731093-1651704.46722689)

array([ True,  True,  True, ...,  True,  True,  True])

In [213]:
np.isclose?

In [223]:
ts_30-(ts_29- 965455.5327731093)

array([-1651704.46722689, -1651704.46722689, -1651704.46722689, ...,
       -1651704.46722689, -1651704.46722689, -1651704.46722689])

In [34]:
for b in maroc_data.active_boards:
    events = np.asarray([Header(i).trigg_n_TS for i in maroc_data.header_board(b)]) 
    print(b, events.shape[0], events[0], events[1], events[-1])

1 1201 1816833406 1 1200
2 1201 2832726102 1 1200
3 1201 1153855658 1 1200
4 1201 2739931666 1 1200
5 1201 2588031744 1 1200
6 1201 1864030104 1 1200
7 1201 2394258874 1 1200
8 1201 2451892098 1 1200
9 1201 2158974892 1 1200
10 1201 2003661804 1 1200
11 1201 2180136338 1 1200
12 1200 2312230670 1 1199
13 1200 2218501458 1 1199
14 1200 2167620508 1 1199
15 1200 2023853124 1 1199
16 1200 4203512684 1 1199
17 1200 2396850 1 1199
18 1200 2330388 1 1199
19 1200 1751335396 1 1199
20 1201 1859795494 1 1200
22 1201 1746147172 1 1200
23 1201 1543875070 1 1200
24 1201 1635067660 1 1200
25 1201 1559567690 1 1200
26 1201 1368928184 1 1200
27 1200 1372784146 1 1200
28 1201 1349505342 1 1200
29 1201 1078333380 1 1200
30 1201 869959158 1 1200


In [89]:
ts_11 = np.asarray([Header(i).TS for i in maroc_data.header_board(1)])[1:]
nevent_11 = np.asarray([Header(i).trigg_n_TS for i in maroc_data.header_board(1)][1:])
ts_12 = np.asarray([Header(i).TS for i in maroc_data.header_board(12)])[1:]
nevent_12 = np.asarray([Header(i).trigg_n_TS for i in maroc_data.header_board(12)][1:])
ts_13 = np.asarray([Header(i).TS for i in maroc_data.header_board(13)])[1:]
nevent_13 = np.asarray([Header(i).trigg_n_TS for i in maroc_data.header_board(13)][1:])

In [115]:
plt.scatter(nevent_11, ts_11, s=5, marker='s',label='board 11')
plt.scatter(nevent_12, ts_12, s=5, marker='o',label='board 12')
plt.scatter(nevent_13, ts_13, s=5, marker='x',label='board 13')
plt.legend(loc='upper right')
plt.xlabel('event id')
plt.ylabel('timestamp')
plt.show()

In [45]:
nevent_11[-30:]

array([1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181,
       1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192,
       1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200])

In [46]:
nevent_12[-30:]

array([1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180,
       1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191,
       1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199])

In [64]:
uniques, uniq_idx, counts = np.unique(nevent_11[1:], return_counts=True, return_inverse=True)

In [65]:
nevent_11[uniq_idx[counts>=2]]

array([], dtype=int64)

In [96]:
uniques, uniq_idx, counts = np.unique(nevent_12[1:], return_counts=True, return_inverse=True)

In [93]:
uniques, uniq_idx, counts = np.unique(nevent_13[1:], return_counts=True, return_inverse=True)

In [97]:
np.where(counts>=2)

(array([249]),)

In [79]:
ts_12[240:260]

array([3583524786, 3587226618, 3600898584, 3601487392, 3623785915,
       3627206582, 3642601649, 3659591246, 3678512548, 3681904857,
       3707938748, 3707938748, 3718197589, 3735061072, 3752113801,
       3780972265, 3832191166, 3833094311, 3842296987, 3844490411])

In [80]:
nevent_12[240:260]

array([241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 251, 253,
       254, 255, 256, 257, 258, 259, 260])

In [98]:
plt.hist(nevent_11, bins=1200,alpha=.5)
plt.hist(nevent_12, bins=1199, alpha=.5)
plt.hist(nevent_13, bins=1199, alpha=.5)


plt.show()

In [87]:
nevent_12[248:255]

array([249, 250, 251, 251, 253, 254, 255])

In [86]:
nevent_12[590:610]

array([591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603,
       604, 605, 606, 607, 608, 609, 610])

In [121]:
nevent_11[1190:]

array([1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200])

In [120]:
nevent_12[1190:]

array([1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199])

In [122]:
nevent_13[1190:]

array([1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199])

In [118]:
np.setdiff1d(nevent_11, nevent_12)

array([ 252, 1200])

In [119]:
nevent_13[565:575]

array([566, 567, 568, 569, 570, 571, 572, 573, 574, 575])

In [106]:
for i, j in enumerate(nevent_27):
    print(i, j)

0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10
10 11
11 12
12 13
13 14
14 15
15 16
16 17
17 18
18 19
19 20
20 21
21 22
22 23
23 24
24 25
25 26
26 27
27 28
28 29
29 30
30 31
31 32
32 33
33 34
34 35
35 36
36 37
37 38
38 39
39 40
40 41
41 42
42 43
43 44
44 45
45 46
46 47
47 48
48 49
49 50
50 51
51 52
52 53
53 54
54 55
55 56
56 57
57 58
58 59
59 60
60 61
61 62
62 63
63 64
64 65
65 66
66 67
67 68
68 69
69 70
70 71
71 72
72 73
73 74
74 75
75 76
76 77
77 78
78 79
79 80
80 81
81 82
82 83
83 84
84 85
85 86
86 87
87 88
88 89
89 90
90 91
91 92
92 93
93 94
94 95
95 96
96 97
97 98
98 99
99 100
100 101
101 102
102 103
103 104
104 105
105 106
106 107
107 108
108 109
109 110
110 111
111 112
112 113
113 114
114 115
115 116
116 117
117 118
118 119
119 120
120 121
121 122
122 123
123 124
124 125
125 126
126 127
127 128
128 129
129 130
130 131
131 132
132 133
133 134
134 135
135 136
136 137
137 138
138 139
139 140
140 141
141 142
142 143
143 144
144 145
145 146
146 147
147 148
148 149
149 150
150 151
151 152
15

In [125]:
nevent_27[990:995]

array([991, 992, 994, 995, 996])

In [ ]:
for b in maroc_data.active_boards:
    events = np.asarray([Header(i).trigg_n_TS for i in maroc_data.header_board(b)]) 
    print(b, events.shape[0], events[0], events[1], events[-1])